apiVersion: batch/v1
kind: Job
metadata:
  name: kube-check-remediate-{{JOB_ID}}
  namespace: kube-system
spec:
  ttlSecondsAfterFinished: 300 # Auto-delete job 5 mins after completion
  backoffLimit: 0 # Don't retry if it fails (fail fast)
  template:
    spec:
      hostPID: true
      hostNetwork: true
      nodeName: {{NODE_NAME}} # Force run on specific node
      containers:
      - name: remediation-agent
        image: kube-check:v1
        imagePullPolicy: IfNotPresent
        # Command to run remediation
        command: ["python", "src/main.py", "remediate", "--check", "{{CHECK_ID}}", "--yes", "--output-format", "json"]
        securityContext:
          privileged: true
        volumeMounts:
        # Critical config paths
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
        - name: var-lib-etcd
          mountPath: /var/lib/etcd
        - name: var-lib-kubelet
          mountPath: /var/lib/kubelet
        - name: etc-systemd
          mountPath: /etc/systemd
        - name: usr-bin
          mountPath: /usr/bin
          readOnly: true
      restartPolicy: Never
      volumes:
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
      - name: var-lib-etcd
        hostPath:
          path: /var/lib/etcd
      - name: var-lib-kubelet
        hostPath:
          path: /var/lib/kubelet
      - name: etc-systemd
        hostPath:
          path: /etc/systemd
      - name: usr-bin
        hostPath:
          path: /usr/bin
